# Site settings
title: Vinicius Cruz
email: vinaocruz@gmail.com
description: I'm Vinicius
baseurl: "/" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Social settings
500px_url:
facebook_url: 
github_url:
gitlab_url: 
googleplus_url: 
instagram_url: 
linkedin_url: https://www.linkedin.com/in/viniciuscruz
pinterest_url:
slack_url:
twitter_url:

# Build settings
markdown: kramdown
